export { PageTemplate } from './PageTemplate'
export { AboutTemplate } from './AboutTemplate'
export { ContactTemplate } from './ContactTemplate'
export { ProjectTemplate } from './ProjectTemplate'
export { HomeTemplate } from './HomeTemplate'
export { ArticleTemplate } from './ArticleTemplate'
